# Server Maintenance Settings

# Maintenance message displayed to users
message = '''Dear Users,

Please be advised that our servers are currently undergoing maintenance to improve our services.
During this time, the servers will be unavailable.
We apologize for any inconvenience this may cause and appreciate your understanding.

Maintenance Period: {start_date_time} to {end_date_time}

Thank you for your patience and support.

Best regards,
Your Company/Team Name'''